chore: add copyright notices
commerce-docs/PlayPI pull request #1
Opened 2023-09-15 15:37 UTC by bdenham

Added Adobe copyright notices to the source code.

2023-09-15 16:02 UTC, jeff-matthews requested changes

2023-09-15 16:02 UTC, jeff-matthews commented on src/AppProvider.jsx
> +NOTICE: Adobe permits you to use, modify, and distribute this file in
Misspelled in all files; do a find/replace

2023-09-15 20:37 UTC, jeff-matthews commented on src/AppProvider.jsx
> +NOTICE: Adobe permits you to use, modify, and distribute this file in
My eyes were playing tricks on me. Sorry.

2023-09-15 20:38 UTC, jeff-matthews approved these changes

2023-09-20 21:41 UTC, bdenham commented
@dshevtsov, good catch on the other PR (adding the correct copyright notice). I added to the same standard notice here.

2023-09-25 16:49 UTC, dshevtsov reviewed
I'm not sure about COPYRIGHT and LICENSE. Could you please point me to the corresponding Adobe guidelines?

2023-09-25 16:57 UTC, bdenham commented
@dshevtsov, yeah, I have no idea. I'm just including the same COPYRIGHT and LICENSE that appears on all developer.adobe.com sites.

2023-10-09 14:23 UTC, dshevtsov commented
If @jeff-matthews is fine with Copiright and License, it's fine with me.

2023-10-09 14:24 UTC, dshevtsov approved these changes

2023-11-04 16:53 UTC, merged